"""Tests for grid2img module.
The majority of these tests are generated by AI.
"""

from grid2img import __version__, Grid, ColourMap
import pytest
from pathlib import Path


def test_version():
	assert __version__ == "1.0.0"


def test_colourmap_defaults_and_add():
	cm = ColourMap()
	# defaults
	assert cm.get_colour("#") == (255, 255, 255)
	assert cm.get_colour(".") == (0, 0, 0)
	# unknown symbol defaults to white
	assert cm.get_colour("Z") == (255, 255, 255)

	# add_colour
	cm.add_colour("X", (10, 20, 30))
	assert cm.get_colour("X") == (10, 20, 30)
	assert "X" in cm.symbols


def test_colourmap_populate_and_symbols():
	cm = ColourMap()
	cm.populate({"A": (1, 2, 3), "B": (4, 5, 6)})
	assert cm.get_colour("A") == (1, 2, 3)
	assert "A" in cm.symbols
	assert "B" in cm.symbols


def test_grid_parse_render_export(tmp_path: Path):
	# create a simple grid file
	content = """!GRIDFILE100
---
###
#.#
"""
	fpath = tmp_path / "simple.grid"
	fpath.write_text(content)

	g = Grid(fpath)
	# parse
	g.parse()
	assert g.width == 3
	assert g.height == 2
	assert "Parsed Grid" in repr(g)

	# render and export
	g.render()
	out = tmp_path / "out.png"
	g.export(out)
	assert out.exists()
	assert out.stat().st_size > 0


def test_parse_invalid_header(tmp_path: Path):
	bad = tmp_path / "bad.grid"
	bad.write_text("""BADHEADER
---
##
##""")
	g = Grid(bad)
	with pytest.raises(ValueError):
		g.parse()


def test_render_without_parse(tmp_path):
	# create a valid file but don't parse
	content = """!GRIDFILE100
---
##
##"""
	fpath = tmp_path / "no_parse.grid"
	fpath.write_text(content)

	g = Grid(fpath)
	with pytest.raises(ValueError):
		g.render()
